name: Squash commits on merge
on:
   merge_group:
       types: [checks_requested]
jobs:
  squash:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the branch
        uses: actions/checkout@v2
      - name: Squash commits
        run: |
          git rebase -i HEAD~n
      - name: Merge the branch
        run: |
          git merge main
